language: python
python:
- '3.5'
- '3.6'
deploy:
  provider: pypi
  user: goettl
  on:
    tags: true
  password:
    secure: IO5ZyPYaDthcnTONkJPJw4bqGxCpqGPxc1XIxkAPzdm0fDH2Iaike7mH4yXjqAwnTHyDyx/a2B0zrhfPJ6c/TYZyLFnjWyf+FAQ9c/37PBuaJr3Z1xIGyl2v8BwSs+yJ/fqYod5jo/v1Bq9B1aMYA5IRGwcavc4X2nFajY6nLQxSFfY9WRjMB03vUodsEoAvhzjQs9CC4S4FYbCqKlmPbkTeHbIeBCQyKgpkbwEVqXR/10s+aAD5JknAhbVArYCMn2cjoJ37sx8Q8olDqcOq7GdRGRbkHdnI/OH0b2OJuA2JdvhZkhSVP7XCZZ4mzqi5QTPa2PuJdlqjuK47h85ZHg5ed+7blBtm/4VEx89EUJ59m8TtGc428C7YduLy4iMfZdH7/5kJKeZeBOqwQ6HoI83JUzOe8XgTEM9vjmnObQWusDA97jHP6hXzdifySQAzqFe34XPk0R+1oO1f/z4P38dENrfBfUDO0Ui3AWLo13NJvj3owcKJ37DBqObPqbvG4kDem0qlb/YRvoapVDQiu6uTwMPBhC5jD8oFFdB2AP0AyU4oI/gMs24qnwRLTSHZsKmHZyCIylb6TbgR/Rha94ONjZ2+RmXHcVJMxru+ZdDtMgZ7j4SqzlKNyVbhSC2+RkiTEi5UhonQ9IHZ3aEnEARh/iLkcYdR2Yi9I52ZUBo=
install:
- pip install -r requirements.txt
script:
- pytest  --ignore tests/test_integration.py
